- name: Install dependencies and configure hostfile
  hosts: all
  become: yes
  roles:
    - role: install_dependencies

- name: Configure SSH
  hosts: master
  become: yes
  become_user: {{ hadoop_user }}
  roles:
    - role: ssh_configuration

- name: Install and configure Hadoop
  hosts: all
  become: yes
  become_user: {{ hadoop_user }}
  roles:
    - role: install_hadoop
    - role: hadoop_configuration

- name: Run HDFS and YARN services on master
  hosts: master
  become_user: {{ hadoop_user }}
  roles:
    - role: start_services
