- name: Install dependencies and configure hostfile
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: install_dependencies

- name: Configure SSH
  hosts: master
  become: yes
  become_user: "{{ hadoop_user }}"
  gather_facts: yes
  roles:
    - role: ssh_configuration

- name: Install and configure Hadoop
  hosts: all
  become: yes
  become_user: "{{ hadoop_user }}"
  gather_facts: yes
  roles:
    - role: install_hadoop
    - role: hadoop_configuration

- name: Start services
  hosts: master
  become_user: "{{ hadoop_user }}"
  gather_facts: yes
  roles:
    - role: start_services

- name: Install and configure Spark
  hosts: master
  become: yes
  become_user: "{{ hadoop_user }}"
  gather_facts: yes
  roles:
    - role: install_spark
    - role: spark_configuration
