---

- name: Spark task
  hosts: master
  become_user: "{{ hadoop_user }}"
  gather_facts: no
  roles:
    - name: Start Services if required
      role: start_services
      when: 'start_services_flag|bool'

    - name: Load texts files to HDFS for later Spark tasks
      role: load_data

    - name: Copy word2vec script and inputs & submit spark job
      role: spark_script
