# Playbook for testing

#- name: Install dependencies and configure hostfile
#  hosts: all
#  become: yes
#  gather_facts: no
#  roles:
#    - role: install_dependencies

#- name: Configure SSH
#  hosts: master
#  become: yes
#  become_user: "{{ hadoop_user }}"
#  gather_facts: no
#  roles:
#    - role: ssh_configuration

#- name: Install and configure Hadoop
#  hosts: all
#  become: yes
#  become_user: "{{ hadoop_user }}"
#  gather_facts: no
#  roles:
#    - role: install_hadoop
#    - role: hadoop_configuration

#- name: Run HDFS and YARN services on master
#  hosts: master
#  become: yes
#  become_user: "{{ hadoop_user }}"
#  gather_facts: no
#  roles:
#    - role: stop_services
#    - role: start_services

- name: Install and configure Spark
  hosts: master
  become: yes
  become_user: "{{ hadoop_user }}"
  gather_facts: no
  roles:
#    - role: install_spark
    - role: spark_configuration

#- name: Load texts files to HDFS for later Spark tasks
#  hosts: master
#  become_user: "{{ hadoop_user }}"
#  gather_facts: no
#  roles:
#    - role: load_data
