---
# tasks file for hadoop_configuration
- name: Create core-site.xml
  template:
    src: core-site.xml.j2
    dest: "{{ hadoop_home }}/etc/hadoop/core-site.xml"
    mode: 0644
  tags: [ add_templates ]

- name: Create hadoop-env.sh
  template:
    src: hadoop-env.sh.j2
    dest: "{{ hadoop_home }}/etc/hadoop/hadoop-env.sh"
    mode: 0644
  tags: [ add_templates ]

- name: Create hdfs-site.xml
  template:
    src: hdfs-site.xml.j2
    dest: "{{ hadoop_home }}/etc/hadoop/hdfs-site.xml"
    mode: 0644
  tags: [ add_templates ]

- name: Create mapred-site.xml
  template:
    src: mapred-site.xml.j2
    dest: "{{ hadoop_home }}/etc/hadoop/mapred-site.xml"
    mode: 0644
  tags: [ add_templates ]

- name: Create yarn-site.xml
  template:
    src: yarn-site.xml.j2
    dest: "{{ hadoop_home }}/etc/hadoop/yarn-site.xml"
    mode: 0644
  tags: [ add_templates ]

- name: Create workers
  template:
    src: workers.j2
    dest: "{{ hadoop_home }}/etc/hadoop/workers"
    mode: 0644
  tags: [ add_templates ]

- name: Add hadoop to path
  copy:
    dest: /etc/profile.d/hadoop-path.sh
    content: "export PATH=$PATH:{{ hadoop_home }}/bin:{{ hadoop_home }}/sbin\nexport HADOOP_HOME={{ hadoop_home }}"
  tags: [ path ]

- name: Create directory of dfs name
  file:
    path: "{{ hdfs_name_dir }}"
    state: directory
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
  when: ( inventory_hostname in groups['master'] )
  tags: [ namenode_dir ]

- name: Create directory of dfs data
  file:
    path: "{{ hdfs_data_dir }}"
    state: directory
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
  when: ( inventory_hostname in groups['workers'] )
  tags:  [ datanode_dir ]
