---
# tasks file for ssh_configuration

- name: Remove old SSH key
  file:
    path: "{{ home_dir }}/.ssh/id_rsa"
    state: absent
  tags: [ ssh_config ]

- name: Remove old SSH public key
  file:
    path: "{{ home_dir }}/.ssh/id_rsa.pub"
    state: absent
  tags: [ ssh_config ]

- name: Generate new SSH key pair
  command: "ssh-keygen -t rsa -q -P '' -f {{ home_dir }}/.ssh/id_rsa"
  tags: [ ssh_config ]

- name: Copy public key to all nodes
  shell: sshpass -p "{{ pass }}" ssh-copy-id -o StrictHostKeyChecking=no {{ user }}@{{ item }}
  with_items: "{{ groups['all'] }}"
  tags: [ ssh_config ]
