---
# tasks file for ssh_configuration

- name: remove old SSH key
  file:
    path: "{{ home_dir }}/.ssh/id_rsa"
    state: absent
  tags: [ ssh ]

- name: remove old SSH public key
  file:
    path: "{{ home_dir }}/.ssh/id_rsa.pub"
    state: absent
  tags: [ ssh ]

- name: generate SSH key pair on master
  command: "ssh-keygen -t rsa -q -P '' -f {{ home_dir }}/.ssh/id_rsa"
  tags: [ ssh ]

#- name: ensure .ssh directory exists on workers
#  file:
#    path: /home/hadoop/.ssh
#    state: directory
#  delegate_to: "{{ item }}"
#  with_items: "{{ groups['workers'] }}"
#  tags: [ ssh ]

- name: copy public key to workers
  shell: sshpass -p "{{ pass }}" ssh-copy-id -o StrictHostKeyChecking=no {{ user }}@{{ item }}
  with_items: "{{ groups['all'] }}"
  tags: [ ssh ]
