- name: install OS dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: {{ os_dependencies }}

- name: install Python dependencies
  pip:
    name: "{{ item }}"
    executable: pip3
    state: present
  with_items: {{ python_dependencies }}
