---
# tasks file for install_dependencies

- name: Install apt dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ os_dependencies }}"
  tags: [ apt_dependencies ]

#- name: install Python dependencies
#  pip:
#    name: "{{ item }}"
#    executable: pip3
#    state: present
#   with_items: "{{ python_dependencies }}"
#  tags: [ python_dependencies ]

- name: Modify /etc/hosts file to include all nodes
  template:
    src: hosts.jinja2
    dest: /etc/hosts
    mode: 0644
  tags: [ hosts_file ]
