---
# tasks file for start-datanodes
- name: delete directories
  become: yes
  file:
    state: absent
    path: '{{ hdfs_dfs_datanode_data_dir }}'
  tags: [ datanode_dir ]

- name: create directories
  become: yes
  file:
    path: '{{ hdfs_dfs_datanode_data_dir }}'
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    state: directory
  tags: [ datanode_dir ]

- name: create datanode service
  become: yes
  template:
    src: hdfs-datanode.service.j2
    dest: /etc/systemd/system/hdfs-datanode.service
    mode: 0640
  notify:
   - daemon reload
   - datanode start
   - datanode enable
  tags: [ add_service_datanode ]
