---
# tasks file for spark_configuration

- name: Create spark-defaults.conf
  template:
    src: spark-defaults.conf.j2
    dest: "{{ spark_home }}/conf/spark-defaults.conf"
    mode: 0644
  tags: [ spark_config ]

- name: Add Hadoop and Spark environment variables to .bashrc and update PATH with Hadoop and Spark binaries directories
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    block: |
      export HADOOP_HOME="{{ hadoop_home }}"
      export HADOOP_CONF_DIR="{{ hadoop_home }}/etc/hadoop"
      export SPARK_HOME="{{ spark_home }}"
      export PATH=$PATH:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:${SPARK_HOME}/bin
    append_newline: true
  tags: [ spark_config ]

- name: Create Spark log directory in HDFS
  command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir -p /spark-logs"
  tags: [ create_spark_log_dir ]

- name: Start Spark History server
  shell: |
      {{ spark_home }}/sbin/stop-history-server.sh
      nohup {{ spark_home }}/sbin/start-history-server.sh
  tags: [ start_spark_history_server ]
