---
# tasks file for spark_configuration

- name: Add Spark binaries to PATH
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    block: |
      export HADOOP_HOME="{{ hadoop_home }}"
      export HADOOP_CONF_DIR="{{ hadoop_home }}/etc/hadoop"
      export SPARK_HOME="{{ spark_home }}"
      export PATH=$PATH:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:${SPARK_HOME}/bin
    append_newline: true

- name: Copy Spark config file
  template:
    src: spark-defaults.conf.j2
    dest: "{{ spark_home }}/conf/spark-defaults.conf"
    mode: 0644

- name: Create Spark log directory in HDFS
  command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir /spark-logs"

- name: Stop Spark history server
  command: "{{ spark_home }}/sbin/stop-history-server.sh"

- name: Start Spark history server
  command: "{{ spark_home }}/sbin/start-history-server.sh"
