---
# tasks file for start_services

- name: format namenode
  shell:
    cmd: "echo Y | {{ hadoop_home }}/bin/hdfs namenode -format"

- name: star HDFS service
  command: "{{ hadoop_home }}/sbin/start-dfs.sh"
#  when: (inventory_hostname in groups['master'])

- name: start YARN service
  command: "{{ hadoop_home }}/sbin/start-yarn.sh"
#  when: (inventory_hostname in groups['master'])
