---
# tasks file for start_services

- name: Format namenode if HDFS filesystem does not exist
  shell:
    cmd: "[[ -d {{ hdfs_name_dir }}/current ]] || {{ hadoop_home }}/bin/hdfs namenode -format -nonInteractive"

- name: Start HDFS service
  command: "{{ hadoop_home }}/sbin/start-dfs.sh"

- name: Start YARN service
  command: "{{ hadoop_home }}/sbin/start-yarn.sh"

- name: Start Spark History server if installed
  command: "[[ -f {{ spark_home }}/sbin/start-history-server.sh ]] && {{ spark_home }}/sbin/start-history-server.sh || echo 'Spark not installed'"
