---
# tasks file for start_services

- name: format namenode
  shell:
    cmd: "echo Y | {{ hdfs_hadoop_home }}/bin/hdfs namenode -format"

- name: start all services HDFS
  command: "{{ hdfs_hadoop_home }}/sbin/start-dfs.sh"
#  when: (inventory_hostname in groups['master'])

- name: start all services YARN
  command: "{{ hdfs_hadoop_home }}/sbin/start-yarn.sh"
#  when: (inventory_hostname in groups['master'])
