---
# tasks file for load_data

- name: Create HDFS input directory
  command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir -p {{ hdfs_input_path }}"
  tags: [ create_task_input_dir ]

- name: Create HDFS output directory
  command: "{{ hadoop_home }}/bin/hdfs dfs -mkdir -p {{ hdfs_output_path }}"
  tags: [ create_task_output_dir ]

- name: Copy input files to the remote node
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
  with_fileglob: "files/*"
  tags: [ load_files ]

- name: Upload files to HDFS
  command: "{{ hadoop_home }}/bin/hdfs dfs -put -f /tmp/{{ item | basename }} {{ hdfs_input_path }}"
  with_fileglob: "files/*"
  tags: [ load_files ]

- name: Verify uploaded files in HDFS
  command: "{{ hadoop_home }}/bin/hdfs dfs -ls {{ hdfs_input_path }}"
  register: hdfs_ls_result
  ignore_errors: yes
  tags: [ verify_task_files ]

- name: Show output of hdfs dfs -ls
  debug:
    msg: "Result of hdfs dfs -ls {{ hdfs_input_path }}:\n{{ hdfs_ls_result.stdout }}"
  tags: [ verify_task_files ]
