
hadoop_user: "{{ hostvars[inventory_hostname]['user'] }}"
hadoop_group: "{{ hostvars[inventory_hostname]['group'] }}"

hdfs_hadoop_home: "/opt/hadoop"
hdfs_fs_defaultFS: "hdfs://192.168.56.20:8020"
hdfs_namenode_port: 8020
hdfs_temp_dir: "/tmp/hadoop/hdfs/tmp"
hdfs_namenode_host: "master"
hdfs_namenode_user: "hadoop"
hdfs_dfs_namenode_name_dir: /var/lib/hadoop/hadoop-name-{{hostvars[inventory_hostname]['name'] | default('master') }}

hdfs_dfs_nameservices: "ha-cluster"
hdfs_dfs_datanode_data_dir: /var/lib/hadoop/hadoop-data-{{hostvars[inventory_hostname]['name'] | default('worker') }}
hdfs_ha_automatic_failover_enabled: "true"

