---
# tasks file for install_hadoop

- name: Check if hadoop JAR file exists
  stat:
    path: '{{ hadoop_tar_path }}'
  register: stat_result
  tags: [ download_hadoop ]

- name: Download hadoop
  get_url:
    url: '{{ hadoop_download_link }}'
    dest: '{{ hadoop_tar_path }}'
  when: not stat_result.stat.exists
  tags: [ download_hadoop ]

- name: Unarchive downloaded file
  unarchive:
    src: '{{ hadoop_tar_path }}'
    dest: '{{ hadoop_install_path }}'
    remote_src: yes
    owner: '{{ hadoop_user }}'
  when: not stat_result.stat.exists
  tags: [ install_hadoop ]

- name: Remove previous installation
  file:
    path: '{{ hadoop_home }}'
    state: absent
  when: not stat_result.stat.exists
  tags: [ install_hadoop ]

- name: Change unarchived directory name
  command: "mv -f {{ hadoop_install_path }}/{{ hadoop_tar_filename }} {{ hadoop_home }}"
  when: not stat_result.stat.exists
  tags: [ install_hadoop ]
